{{- if not .Values.multiPod.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}
  labels:
    app: galera-k8s
spec:
  serviceName: {{ .Values.global.serviceName }} 
  replicas: 1 # only single pod
  selector:
    matchLabels:
      app: galera-k8s
  template:
    metadata:
      labels:
        app: galera-k8s
    spec:
      containers:
        - name: galera
          image: {{ template "galera.image" . }} 
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          ports:
            - containerPort: 3306
              name: mariadb
          env:
            - name: MULTI_POD_ENABLED
              value: "F"
            - name: SERVICE_NAME
              value: {{ .Values.global.serviceName }} 
            # [FIXME] user may want to set cluster name
            - name: MARIADB_CLUSTER_NAME
              value: galera-k8s-cluster 
          volumeMounts:
            - name: galera-k8s-pvc
              mountPath: /var/lib/mysql
              {{- if .Values.persistence.enabled }}
              subPath: persistence.subPath
              {{- end }}
          resources:
{{ toYaml .Values.resources | indent 12 }} 
      imagePullSecrets:
        - name: {{ .Values.imageCredentials.name }}
      volumes:
        {{- if not .Values.persistence.enabled }}
        - name: galera-k8s-pvc
          emptyDir: {}
        {{- end }}
      {{- if .Values.global.nodeselector }}
      nodeSelector:
{{ toYaml .Values.global.nodeSelector | indent 8 }}
      {{- end }}

  {{- if .Values.persistence.enabled }}
  volumeClaimTemplatess:
    - metadata:
        name: galera-k8s-pvc
      spec:
        accessModes:
          - {{ .Values.persistence.accessMode | quote }}
        resources:
          requests:
            storage: "{{ .Values.persistence.size }}"
        {{- if .Values.persistence.storageClass }}
        {{- if (eq "-" .Values.persistence.storageClass) }}
        storageClassName: ""
        {{- else }}
        storageClassName: "{{ .Values.persistence.storageClass }}"
        {{- end }}
        {{- end }}
  {{- end }}
{{- end }}
