global:
  # nodeSelector:
  #   server: my-server 
  nodeSelector: {}
  # service name(set the serviceName in StatefulSet and metadata.name in Service to this one)
  serviceName: galera-k8s-svc

multiPod:
  enabled: true 
  # replicaCount is ignored when multiPod.enabled = true
  replicaCount: 3

nodePort:
  # port is ignored when nodePort.enabled = false
  enabled: true 
  nodeServiceName: galera-k8s-node
  port: 31002 

image:
  registry: docker.io 
  # registry: my.registry.com 
  repository: josh9191/galera-k8s
  tag: v0.0.0
  pullPolicy: IfNotPresent

imageCredentials:
  name: galera-k8s-cred # should not be empty 
  registry: docker.io 
  username: ""
  password: "" 

resources:
  limits:
    cpu: 1000m 
    memory: 1024M 
  requests:
    cpu: 500m 
    memory: 1024M 

persistence:
  enabled: true 
  size: 5Gi 
  # matchLabels: 
  #   app: db-root-vol
  matchLabels: {}
  # storageClass: - 
  storageClass: nfs-client
  accessMode: ReadWriteMany
  subPath: mariadb
